### ISSUE TITLE
Tarea Imágenes

### ISSUE THREAD

**Issue by lau-droid** [666Jennyfer666/turismo#24]
Buscar al menos 4 imágenes de:
- (LAS) Localidades (Erick, Facu (se reparten ellos))
- Información útil: hospedajes, gastronomía y transporte (Fran (hospedaje y transporte) y Erick (gastronomía))
- Qué visitar: Lugares Turísticos, Cultura y Naturaleza (Aarón y Lourdes (se reparten ellos))

Adjuntar las imágenes acá (en la tarea). Luego, lo vamos a subir al repositorio.

**Comment by FaHer052005** [comment]
![villa-dolores-1](https://github.com/666Jennyfer666/turismo/assets/133163657/35077b60-ecc9-49db-9842-16129fde7ba6)
![8daa415b30c39134c5c47787bfdf616f](https://github.com/666Jennyfer666/turismo/assets/133163657/951755eb-ad49-4950-91d4-59704b0fe85e)
![DSC06126](https://github.com/666Jennyfer666/turismo/assets/133163657/7c495757-0fb3-44a2-9ab2-16102cbacf84)
![DSC_8779](https://github.com/666Jennyfer666/turismo/assets/133163657/2d71f306-0f99-4715-afac-d0d48dc11740)
![rio-mina-clavero-una-maravilla-de-aguas-paradisiacas-5256-mainImage-0](https://github.com/666Jennyfer666/turismo/assets/133163657/694419a9-107c-42ed-b37a-8a319b8da161)
![Uploading djcarlitox1987.jpg…]()

**Comment by FaHer052005** [comment]
![CuraBrochero01-secretaria](https://github.com/666Jennyfer666/turismo/assets/133163657/c7dedbac-36c3-460f-af63-7445bd128229)
![Uploading Monumento_al_Cura_Brochero_Plaza_Centenario_de_Villa_Cura_Brochero.jpg…]()

**Comment by 666Jennyfer666** [comment]
![imagen2aimara(hotel)](https://github.com/666Jennyfer666/turismo/assets/134174045/0f9dd687-fbae-4cac-9513-f1105754f558)
![imagen2altodelsol(cabaña)](https://github.com/666Jennyfer666/turismo/assets/134174045/7b81822c-6e92-442c-804e-300fe8b32d74)
![imagen2apartstella(hotel)](https://github.com/666Jennyfer666/turismo/assets/134174045/74b049bc-8d6b-412b-8a09-0bc4968d331e)
![imagen2laalbertina(cabaña)](https://github.com/666Jennyfer666/turismo/assets/134174045/c77e8b85-6af3-4510-a31e-386fcfd708e2)
![imagen3aimara(hotel)](https://github.com/666Jennyfer666/turismo/assets/134174045/021410dd-dc76-4876-a683-101149448cba)
![imagen3laslilas(hotel)](https://github.com/666Jennyfer666/turismo/assets/134174045/1c09ec43-162d-41fa-9654-14ca1cc79932)
![imagen3mountainsvilladolores(hospejade)](https://github.com/666Jennyfer666/turismo/assets/134174045/fdddf1f4-aa96-4837-9f2c-692cb542e7dd)
![imagenaltodelsol(cabaña)](https://github.com/666Jennyfer666/turismo/assets/134174045/ec50584e-e49b-4ce5-9907-e19a6e107b0a)
![imagenesaparhotel(hotel)](https://github.com/666Jennyfer666/turismo/assets/134174045/b405d938-750b-41db-95b8-0626139b9898)
![imagenesdebarrancacurabrochero(hotel)](https://github.com/666Jennyfer666/turismo/assets/134174045/157a8ade-fc93-4808-9902-d2c120b6e311)
![imageneslaalbertina(cabaña)](https://github.com/666Jennyfer666/turismo/assets/134174045/885b4ca4-1fd0-43b5-ba3c-967c419feacc)
![imagenlaalbertina(cabaña)](https://github.com/666Jennyfer666/turismo/assets/134174045/c642f25d-3cc9-4e17-b661-e63c6b36205e)

en el nombre de la imagen puse el nombre de el establecimiento y en que parte de las listas del html pertenece (cabañas o hoteles) las img son todas de Hospedajes.

**Comment by 666Jennyfer666** [comment]
![imagendelaterminalvilladolores(primeroenlalista)](https://github.com/666Jennyfer666/turismo/assets/134174045/72524a24-6594-43a5-a82c-e4bd57de5d45)
![imagendeterminal(laprimeraenlalista)](https://github.com/666Jennyfer666/turismo/assets/134174045/7f29ff74-7b90-4436-ab97-2e3fca54c4f6)
![imagenlogopanaholma(terceroenlalista)](https://github.com/666Jennyfer666/turismo/assets/134174045/9fd8c87b-c9b8-491d-8aa1-74c8a1e72319)
![imagenpanaholma(terceroenlalista)](https://github.com/666Jennyfer666/turismo/assets/134174045/246742d3-352d-46b4-a19a-71180ec880b1)
![imagenpanaholma(terceroenlalista)h](https://github.com/666Jennyfer666/turismo/assets/134174045/89425101-16cf-4503-af2a-7b84c52b680c)
![imagenterminalenminaclaver(cuartoenlalistad)](https://github.com/666Jennyfer666/turismo/assets/134174045/a96b4f97-575e-44ff-8b14-43ced50002fc)
![imagenterminalenminaclavero(cuartoenlalista)](https://github.com/666Jennyfer666/turismo/assets/134174045/d1eb7a7d-5173-4258-8388-644c3eb87a86)
![logoplataforma10(segundoenlalista)](https://github.com/666Jennyfer666/turismo/assets/134174045/2715ff17-0cbe-4dbc-80ef-afe80ab401ce)
![plataforma10(segundoenlalista)](https://github.com/666Jennyfer666/turismo/assets/134174045/5ee78650-4842-40bc-bf42-1a03beb3c5c2)


estas son las imagenes de  Trasporte.htm y cada imagen tiene el nombre a que empresa o terminal pertenece :(.

**Comment by lau-droid** [comment]
![AMDMC1](https://github.com/666Jennyfer666/turismo/assets/134238109/6531d3c1-4cde-4ed6-bf8b-3e869fe01e5a)
![AMDMC2](https://github.com/666Jennyfer666/turismo/assets/134238109/cbbd7863-77f5-4329-ab27-76c9404d8f6a)
![AMDMC3](https://github.com/666Jennyfer666/turismo/assets/134238109/cc4994f5-1267-426a-91c1-4be1a75885cc)
![AMDMC4](https://github.com/666Jennyfer666/turismo/assets/134238109/8233be7d-8bf7-4a94-ac4c-b948484d3b59)
![CDLPS1](https://github.com/666Jennyfer666/turismo/assets/134238109/abfeb3a0-5014-4daf-a070-a64f2d6c6be5)
![CDLPS2](https://github.com/666Jennyfer666/turismo/assets/134238109/5a95ba43-c341-4b02-a944-b799871eed11)
![CDLPS3](https://github.com/666Jennyfer666/turismo/assets/134238109/dc00cd19-8354-4e5c-a6b4-108c15aaf875)
![CDLPS4](https://github.com/666Jennyfer666/turismo/assets/134238109/0986531c-cbd8-48a7-9f73-44fea8fd289b)
![CYTSP1](https://github.com/666Jennyfer666/turismo/assets/134238109/9c783eb2-b6c9-47ad-8940-3333264be032)
![CYTSP2](https://github.com/666Jennyfer666/turismo/assets/134238109/db93aea0-72db-4da9-9abb-5c7ed5c514b2)
![CYTSP3](https://github.com/666Jennyfer666/turismo/assets/134238109/f13c440d-8b3a-4ec5-818c-5d0d8966f20c)
![EFSP1](https://github.com/666Jennyfer666/turismo/assets/134238109/7b884813-9c01-4ecb-b56c-12aa664a564c)
![EFSP2](https://github.com/666Jennyfer666/turismo/assets/134238109/8c78588e-f123-4657-8fb4-ae5ae984fd25)
![EFSP3](https://github.com/666Jennyfer666/turismo/assets/134238109/88242f34-ddf9-4e29-8074-911033621ed8)
![EFSP4](https://github.com/666Jennyfer666/turismo/assets/134238109/e6de97ee-1af0-4d63-a027-5776e5edfa57)
![IDLVDLML1](https://github.com/666Jennyfer666/turismo/assets/134238109/5ad32336-fdda-4de2-81ef-7e2f062fbf51)
![IDLVDLML2](https://github.com/666Jennyfer666/turismo/assets/134238109/d71cd6c9-8e48-4161-908e-0aa2f211c5f2)
![IDLVDLML3](https://github.com/666Jennyfer666/turismo/assets/134238109/9a159c2b-971c-4bbe-b651-3c39996885fe)
![IDLVDLML4](https://github.com/666Jennyfer666/turismo/assets/134238109/853a820c-af5c-4874-b7bd-a2e567d1a3ff)
![ISJBN1](https://github.com/666Jennyfer666/turismo/assets/134238109/50c0891e-4b86-45b3-94f4-86eef0dbf966)
![ISJBN2](https://github.com/666Jennyfer666/turismo/assets/134238109/f7d16127-1e7a-4f9d-99ae-a483d8c8a13d)
![ISJBN3](https://github.com/666Jennyfer666/turismo/assets/134238109/aa458c5d-598b-4311-ba72-794744e6ba84)
![ISJBN4](https://github.com/666Jennyfer666/turismo/assets/134238109/ad7350ee-f83a-4abd-b8ec-2a2dbd91a222)
![MALIP1](https://github.com/666Jennyfer666/turismo/assets/134238109/679d1604-3880-4ff2-bae3-57bb5b904608)
![MALIP2](https://github.com/666Jennyfer666/turismo/assets/134238109/5c21f244-b32d-4262-88d4-10f0e33ea839)
![MALIP3](https://github.com/666Jennyfer666/turismo/assets/134238109/f2aab042-74de-4b8e-abf6-da2d7cbb09ab)
![MBVCB1](https://github.com/666Jennyfer666/turismo/assets/134238109/e0052864-250a-47c2-87a0-bd9c167cf973)
![MBVCB2](https://github.com/666Jennyfer666/turismo/assets/134238109/dfcdf680-0ad5-4ead-8bd0-ad0868288811)
![MBVCB3](https://github.com/666Jennyfer666/turismo/assets/134238109/05bfd49b-e51f-4ada-aea6-d47d8d26ea4f)
![MBVCB4](https://github.com/666Jennyfer666/turismo/assets/134238109/02558cf2-9f41-4b6a-b7a8-996b176f0395)
![MDVD1](https://github.com/666Jennyfer666/turismo/assets/134238109/caa3f08c-02c2-4baf-b303-a222ad29b3a2)
![MDVD2](https://github.com/666Jennyfer666/turismo/assets/134238109/1719e03a-5dd7-4c6c-bdeb-40be750267ac)
![MPCSMC1](https://github.com/666Jennyfer666/turismo/assets/134238109/acfa74c3-2950-44a1-8d68-391de0ca69e0)
![MPCSMC2](https://github.com/666Jennyfer666/turismo/assets/134238109/ea72fa0c-599f-41cc-8dee-e53c4b101f2d)
![MPCSMC3](https://github.com/666Jennyfer666/turismo/assets/134238109/8e39b3a5-03c7-475e-a9db-e163e6ea574f)
![MPCSMC4](https://github.com/666Jennyfer666/turismo/assets/134238109/8b74a112-433a-4b9a-92ec-b2bd4e91cb74)
![MPRN1](https://github.com/666Jennyfer666/turismo/assets/134238109/d3e8af4a-c142-4373-859d-afad9d43a86e)
![MPRN2](https://github.com/666Jennyfer666/turismo/assets/134238109/6e880299-25b0-4656-b18e-e61bd3011fed)
![MPRN3](https://github.com/666Jennyfer666/turismo/assets/134238109/2a744f93-9505-4435-8d86-95a52e0c3378)
![MPRN4](https://github.com/666Jennyfer666/turismo/assets/134238109/fc936391-19b9-4f32-905d-fb43fa329e10)
![SNSDTVCB1](https://github.com/666Jennyfer666/turismo/assets/134238109/e165741b-c94d-4c83-a7e3-2bece3d97ee3)
![SNSDTVCB2](https://github.com/666Jennyfer666/turismo/assets/134238109/859000dc-1348-4c78-8969-b02db65de892)
![SNSDTVCB3](https://github.com/666Jennyfer666/turismo/assets/134238109/3de106e8-c9af-4f8f-b5d8-ade040ff4741)
![SNSDTVCB4](https://github.com/666Jennyfer666/turismo/assets/134238109/e727066d-3301-46cf-9e4b-b9971788f68e)
![TEVD1](https://github.com/666Jennyfer666/turismo/assets/134238109/e4449883-b196-4c32-b29b-3584ea431f41)
![TGVD1](https://github.com/666Jennyfer666/turismo/assets/134238109/06f71027-92ac-4610-bd3d-f46ad191f8f7)
![TGVD2](https://github.com/666Jennyfer666/turismo/assets/134238109/29db7170-9525-4dc6-97b3-5a2ac820e1e6)
![TGVD3](https://github.com/666Jennyfer666/turismo/assets/134238109/2ede4d33-f5b4-4e69-a7cb-b864a31e9492)
![TGVD4](https://github.com/666Jennyfer666/turismo/assets/134238109/f8aa7da3-e113-4fa7-b856-3a30d591f6f5)

Mis imágenes de Cultura

**Comment by lau-droid** [comment]
Las imágenes de Naturaleza están subidas en el repositorio.
No me deja subirlas acá.

**Comment by lourdesne** [comment]
TERMINADO.
