### ISSUE TITLE
Tarea: Historia de Usuario Consultas

### ISSUE THREAD

**Issue by lau-droid** [666Jennyfer666/turismo#6]
Historia de Usuario:
COMO el cliente QUIERO consultar PARA PODER responder mis dudas.

Hacer la estructura de tu página web, si podés, agregar estilos y algún tipo de código.

**Comment by FaHer052005** [comment]
Aaron ya lo tengo, pero igual mucho no hice 
osea le agregue muy poco de CSS

**Comment by FaHer052005** [comment]
El tema es que no se como mandar el codigo jajajaja

**Comment by lau-droid** [comment]
Tu tarea está finalizada.

Agregá tu tarea a Done/Hecho en el Project/Proyecto.
