### ISSUE TITLE
Tarea: Historia de Usuarios Información útil

### ISSUE THREAD

**Issue by lau-droid** [666Jennyfer666/turismo#9]
Historia de Usuario:
COMO el cliente QUIERO tener información sobre transportes y sus rutas, tener información de alojamientos PARA PODER organizar mi desplazamiento sobre el viaje y los lugares dónde me quiero quedar.

Hacer la estructura de tu página web, si podés, agregar estilos y algún tipo de código.

**Comment by 666Jennyfer666** [comment]
ya lo termine :)
